### ISSUE TITLE
Add browser based models, highlight inference-only models

### ISSUE THREAD

**Issue by faroit** [ysh329/deep-learning-model-convertor#12]
1. would it be interesting to add conversion tools that allow to convert to pure javascript based models like [deeplearn.js](http://deeplearnjs.org/)? I could make a PR for this...
2. I think it would make sense to highlight the inference-only frameworks, maybe using a specific icon?

**Comment by ysh329** [comment]
@faroit Thanks your issue in advance. The inference-only frameworks're welcomed, too! I just have a look about `deeplearn.js`, which not only support training but also inference, great! But what a pity, I searched using keywords such as `deeplearn.js`, `model`, `tensorflow` and `convert` and found no relative repository.

Good idea! I'll add some inference-only frameworks using a specific icon. 👍 The inference-only-frameworks are useful especially for those embedding system or resource-limited devices or a convenient demo.
