### ISSUE TITLE
Caffe to pytorch

### ISSUE THREAD

**Issue by sunithak** [ysh329/deep-learning-model-convertor#16]
Hello,
My name is sunitha. I would like to convert https://github.com/alexgkendall/caffe-posenet/blob/master/models/bvlc_googlenet/deploy.prototxt caffe code into pytorch. I am using arch linux in my system. How can i use your convertor to convert the code? Thank you

**Comment by kitstar** [comment]
Hi, You can try general converter [MMdnn](https://github.com/Microsoft/MMdnn), which can convert caffe models to pytorch.
