### ISSUE TITLE
Converter caffe to caffe2

### ISSUE THREAD

**Issue by LennartHH** [ysh329/deep-learning-model-convertor#19]
Thank you for this very helpful compilation of available converters! I came accross a conversion tool for caffe -> caffe2 that is not included in the table. You might want to add it. See 
 [python script](https://github.com/caffe2/caffe2/blob/master/caffe2/python/caffe_translator.py) and its [description](https://caffe2.ai/docs/caffe-migration.html).

**Comment by ysh329** [comment]
Added. Thanks my big brother 🤣
