### ISSUE TITLE
Convert from Darknet to TensorFlow

### ISSUE THREAD

**Issue by jinyu121** [ysh329/deep-learning-model-convertor#27]
[This repo](https://github.com/jinyu121/DW2TF) can convert Darknet to TensorFlow, but can not convert back yet.

Only support `convolution` layer now. More layer types will be add soon, or LATER.

**Comment by ysh329** [comment]
Great, jinyu! Welcome to PR 👍

**Comment by ysh329** [comment]
Thanks and added. 👍
