### ISSUE TITLE
can kears model converts to darknet ?

### ISSUE THREAD

**Issue by Aurora11111** [ysh329/deep-learning-model-convertor#42]

**Comment by ysh329** [comment]
You can find and try relative converters in `readme`.

**Comment by Aurora11111** [comment]
@ysh329 thank your answer,I hvae checked the README,there is no directly method to convert kears model to darknet ,so I have to convert kears model to pytorch firstly ,then convert pytorch model to darknet?

**Comment by ysh329** [comment]
@Aurora11111 Yeah, or you can have a look on MMdnn project.
